# Log Settings
logging:
  level:
    org:
      hibernate: WARN
      springframework:
        cloud: INFO
        security: INFO
        boot:
          web: INFO
      apache: WARN
      # catalina: WARN
    com:
      zaxxer: WARN
      netflix: WARN
      # discovery: WARN
      # eureka: WARN
      devamatre: DEBUG


# Eureka Client Settings
server:
  port: ${EUREKA_CLIENT_PORT:8416}

#Spring Settings
spring:
  application:
    # registry-client
    name: ${EUREKA_CLIENT_NAME:eureka-client}

#cloud:
#  config:
#    label: ${spring.profiles.active}
#    discovery:
#      enabled: true

# http://localhost:8316/eureka/
# Eureka/Registry Service Settings
registry:
  service:
    port: ${EUREKA_SERVICE_PORT:8316}

## Eureka Settings
eureka:
  instance:
    hostname: ${EUREKA_CLIENT_HOSTNAME:localhost}
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      # where defaultZone should hold the value of your Eureka/Registry Service.
      defaultZone: ${REGISTRY_SERVICE_URL:http://${eureka.instance.hostname}:${registry.service.port}/eureka/}
#    healthcheck:
#      enabled: true
