# http://localhost:8761/eureka/
#Spring Settings
spring:
  application:
    # eureka-service
    name: ${EUREKA_SERVICE_NAME:eureka-service}

# Server Settings
# The default port which eureka naming server
# Eureka Settings
eureka:
  instance:
    hostname: ${EUREKA_SERVICE_HOSTNAME:localhost}
    # only for local development. remove this setting in production and thus default to 30 seconds.
    leaseRenewalIntervalInSeconds: 2
    preferIpAddress: false

  server:
    waitTimeInMsWhenSyncEmpty: 0

  client:
    register-with-eureka: false
    fetch-registry: false
    #    registerWithEureka: false
    #    fetchRegistry: false
    service-url:
      # In the preceding example, "defaultZone" is a magic string fallback value that provides the service URL for
      # any client that does not express a preference (in other words, it is a useful default).
      # where defaultZone should hold the value of your Eureka/Registry Service.
      # end point of load balancing server (registry service)
      # defaultZone: http://admin:pwd@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---

config:
  activate:
    on-profile: ${ACTIVE_PROFILE_NAME:cloud}

eureka:
  instance:
    ## set the host name explicitly when in Cloud Foundry.
    hostname: ${EUREKA_SERVICE_HOSTNAME:localhost}
    # make sure in the cloud we use proper default values.
    leaseRenewalIntervalInSeconds: 30
    ## This information will be part of the InstanceInfo returned by DiscoveryClient / EurekaClient.
    ## Unfortunately, these have to be specified explicitly, since Eureka creates these URLs wrongly
    ## when running on CF.
    ## See: https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html
    #${REGISTRY_SERVICE_HOMEPAGE_URL:http://${eureka:instance:hostname}:${server:port}/eureka/}
    homePageUrl: https://${eureka.instance.hostname}/
    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    secureHealthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    metadata-map:
      # Adding information about the application GUID and app instance index to
      # each instance metadata. This could be used for setting the X-CF-APP-INSTANCE header
      # to instruct Go-Router where to route.
      cfAppGuid: ${EUREKA_SERVICE_HOSTNAME:localhost}
      cfInstanceIndex: ${INSTANCE_INDEX}
