#FROM java:8
#ADD Eureka-Service-0.0.1-SNAPSHOT.jar app.jar
#VOLUME /tmp
#VOLUME /build
#RUN bash -c 'touch /app.jar'
#EXPOSE 8888
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]